# Generated by Django 4.2.30 on 2026-04-26 13:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paise', models.BigIntegerField()),
                ('bank_account_id', models.CharField(max_length=50)),
                ('idempotency_key', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='merchants.merchant')),
            ],
            options={
                'db_table': 'payouts',
                'indexes': [models.Index(fields=['merchant', 'status'], name='payouts_merchan_44832a_idx'), models.Index(fields=['status', 'created_at'], name='payouts_status_ef59be_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.UniqueConstraint(models.F('merchant'), models.F('idempotency_key'), name='unique_merchant_idempotency'),
        ),
    ]
