# Generated by Django 4.2.30 on 2026-04-27 06:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paise', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('from_merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='merchants.merchant')),
                ('to_merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='merchants.merchant')),
            ],
            options={
                'db_table': 'transfers',
                'indexes': [models.Index(fields=['from_merchant', 'created_at'], name='transfers_from_me_347035_idx'), models.Index(fields=['to_merchant', 'created_at'], name='transfers_to_merc_f05923_idx')],
            },
        ),
    ]
