# Generated by Django 4.2.30 on 2026-04-26 13:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount_paise', models.BigIntegerField()),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, choices=[('payment', 'Payment'), ('payout', 'Payout')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='merchants.merchant')),
            ],
            options={
                'db_table': 'ledger_entries',
                'indexes': [models.Index(fields=['merchant', 'created_at'], name='ledger_entr_merchan_491d5c_idx'), models.Index(fields=['merchant', 'entry_type'], name='ledger_entr_merchan_2b8c6e_idx')],
            },
        ),
    ]
